MyApp/admin/routes.py
from flask import Blueprint, render_template, request, flash, redirect,url_for, json, abort
from MyApp import db
from datetime import datetime
from flask_login import login_user, logout_user, login_required
from MyApp.models import User, isConnected

admin = Blueprint('admin', __name__)

@admin.route("/", methods=['GET', 'POST'])
@admin.route("/admin", methods=['GET', 'POST'])
def admin_login():
    email_data = 'shkhaider2015@gmail.com'
    pass_data = '123'
    if request.method == 'POST':
        email_data = request.form['email']
        pass_data = request.form['password']
        print(email_data, pass_data)
        user = User.query.filter_by(email=email_data).first()
        if user and (user.password == pass_data):
            login_user(user, remember=True)
            return redirect(url_for('admin.admin_main'))

        else:
            flash("Unsuccessfull login", 'danger')
    else:
        print("kk")

    return render_template("index.html")


@admin.route("/home")
@login_required
def admin_main():
    if not isConnected():
        print("---------------------------Connection Error------------")
        return abort(404, description="Resource not found")
    users = db.child("Users").get()
    userList = list()
    if users.val():
        for user in users.each():
            profile = user.val()
            data = profile['Profile']
            print("My data : " + str(data))
            userList.append(data)
    return render_template("admin_home_page.html", users=userList)

@admin.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('admin.admin_login'))


@admin.route("/order")
@login_required
def admin_order():
    if not isConnected():
        print("---------------------------Connection Error------------")
        return abort(404, description="Resource not found")
    orders = db.child("Orders").get()
    objectList = list()
    for order in orders.each():
        print("Loop Runs ")
        print(order.val())
        objectList.append(dict(order.val()))
    print(objectList)
    objectList.reverse()
    return render_template("admin_order.html", objectList=objectList)


@admin.route("/accept_process", methods=['POST'])
@login_required
def process_accept():
    if not isConnected():
        print("---------------------------Connection Error------------")
        return abort(404, description="Resource not found")
    data = None
    if request.method == 'POST':
        data = request.form['data']
        user_id = str(data[:-13:1])
        order_id = str(data[-13::1])
        pair = {'accepted' : True}
        print(user_id)
        print(order_id)
        db.child("Orders").child(order_id).update(pair)
        db.child("Users").child(user_id).child("Orders").child(order_id).update(pair)

        return json.dumps({'status':'OK'})
    print("Not a Post Request")


@admin.route("/profile/<string:uid>")
@login_required
def user_profile(uid):
    if not isConnected():
        print("---------------------------Connection Error------------")
        return abort(404, description="Resource not found")
    profile_path = db.child("Users").child(uid).child("Profile").get()
    orders_path = db.child("Users").child(uid).child("Orders").get()
    profile = dict(profile_path.val())

    if orders_path.val():
        orders = dict(orders_path.val())
    else:
        orders = None
    
    return render_template("profile.html", profile=profile, orders=orders)

MyApp/foods/routes.py
from flask import Blueprint, render_template, request, redirect, flash, url_for, json, abort
from MyApp import storage, db
from werkzeug.utils import secure_filename
from flask_login import login_required
from MyApp.models import isConnected


foods = Blueprint('foods', __name__)

@foods.route('/add_foods')
@login_required
def add_foods():
    print("add foods called")
    return render_template("foods_add.html")

def downloadUri(image, token):
    imageUri = None
    imageUri = storage.child("Foods/logos/" + secure_filename(image.filename)).get_url(token)
    return imageUri


@foods.route('/add_foods/process_data', methods=['POST'])
@login_required
def process_data():
    if request.method == 'POST':
        foodName = request.form['foodName']
        foodPrice = request.form['foodPrice']
        foodImage = request.files['foodImage']
        if foodImage and foodName and foodPrice:
            upload = storage.child("Foods/logos/" + secure_filename(foodImage.filename)).put(foodImage)
            filePath = downloadUri(foodImage, upload['downloadTokens'])
            if filePath:
                data = { 'foodName' : foodName, 'foodPrice' : foodPrice, 'foodImageUri' : filePath }
                db.child("Foods").child(foodName).set(data)
                return redirect(url_for("foods.foods_list"))
            else:
                print("File Path Return empty")
        else:
            print("some data field may b empty")

    return render_template("foods_add.html")


@foods.route('/foods_list')
@login_required
def foods_list():
    if not isConnected():
        print("---------------------------Connection Error------------")
        return abort(404, description="Resource not found")
    tmpData = db.child("Foods").get()
    data = dict(tmpData.val())
    print(data)
    return render_template("foods_list.html", data=data)


def availability(name, condition):
    pair = {'availability' : condition }
    db.child("Foods").child(name).update(pair)

@foods.route('/foods_list/availability', methods=["POST"])
@login_required
def processAvailability():
    if not isConnected():
        print("---------------------------Connection Error------------")
        return abort(404, description="Resource not found")
    condition = None
    data = { 'status' : 'ok', 'condition' : condition}
    if request.method == 'POST':
        itemName = request.form['itemName']
        con = request.form['condition']
        if con == "true":
            condition = True
        else:
            condition = False
        availability(itemName, condition)
        print(condition)
        data['condition'] = condition 

    return json.dumps(data)

MyApp/messanger/routes.py
from flask import Blueprint, render_template, request, flash, redirect,url_for, json, abort
from MyApp import db
import time
from flask_login import login_required
from MyApp.models import isConnected
from datetime import datetime


messanger = Blueprint('messanger', __name__)

previous_data = dict()

def get_data(key):
    if not isConnected():
        print("---------------------------Connection Error------------")
        return abort(404, description="Resource not found")
    print(key)
    tmp = db.child("Users").child(key).child("Chat").get()
    dicts = dict(tmp.val())
    print(dicts)
    return dicts




@messanger.route("/send_message", methods=['POST'])
@login_required
def message_send():
    data = None
    msg = None
    if not isConnected():
        print("---------------------------Connection Error------------")
        return abort(404, description="Resource not found")
    if request.method == 'POST':
        time = int(datetime.now().timestamp()) * 1000
        data = request.form['data']
        msg = str(request.form['msg'])
        senderid = request.form['senderid']
        image_path =  "https://firebasestorage.googleapis.com/v0/b/canteen-management-syste-e183d.appspot.com/o/Admin%2Fburger.png?alt=media&token=b6731782-c9a6-452a-8bb6-46a4ce8a8321"
        if data == 'adminn' and msg != None:
            print("Admin Call")
            pushData = dict({ 
                'senderId' : "17352015",
                'senderName' : "Admin",
                'senderEmail' : "admin@gmail.com",
                'senderProfileUri' : image_path,
                'msgTime' : time,
                'msg' : msg
                })

            print(f"The Sender Id : {senderid} and time : {time} ")
            db.child("Users").child(senderid).child("Chat").child(time).set(pushData)
            return json.dumps({'status' : 'ok'})
            
        elif data == "page":
            return json.dumps(get_data(senderid))
        else:
            print("Another Call")
            
        return json.dumps({'status' : 'ok'})
    print("Not a post Request")

@messanger.route("/chat/<string:key>", methods=['POST', 'GET'])
@login_required
def chat(key):
    if not isConnected():
        print("---------------------------Connection Error------------")
        return abort(404, description="Resource not found")
    return render_template("chat_jq.html", key=key)

@messanger.route("/accept_chat_process", methods=['POST', 'GET'])
@login_required
def chat_process():
    if not isConnected():
        print("---------------------------Connection Error------------")
        return abort(404, description="Resource not found")
    global previous_data
    key = request.form['key']
    m_type = request.form['m_type']
    data = dict()
    
    if m_type == 'send':
        print("send request")
        msg = request.form['msg']
        msgTime = int(time.time()) * 1000
        set_data = {
            'senderName' : 'admin',
            'senderId' : '17352015',
            'senderEmail' : 'admin@gmail.com',
            'senderProfileUri' : 'https://firebasestorage.googleapis.com/v0/b/canteen-management-syste-e183d.appspot.com/o/Admin%2Fburger.png?alt=media&token=b6731782-c9a6-452a-8bb6-46a4ce8a8321',
            'msgTime' : msgTime,
            'msg' : msg
        }
        db.child("Users").child(key).child("Chat").child(msgTime).set(set_data)
        data = get_data(key)
        previous_data = data
        
    elif m_type == 'detect_changes':
        next_data = get_data(key)
        if not bool(previous_data):
            print("Previous Dict is empty")
            previous_data = next_data
            return json.dumps({'status' : 'initialize'})
        else:
            if previous_data == next_data:
                print("Nothing Changes")
                return json.dumps({'status' : 'nothing changed'})
            else:
                data = next_data
                previous_data = next_data
                print("Somthing changes")
    elif m_type == "refresh":
        data = get_data(key)
        previous_data = data


    
    
    return json.dumps(data)

MyApp/templates/admin_home_page.html
{% extends "layout.html" %}

{% block content %}

<div class="container">
    <h1 class="mt-5 myFonts" >User List</h1>
    <br>
    <hr>

   {% for user in users %}
    <div class="row mt-3">

        <div class="col-md-1">
            <!-- Profile Image -->
            <img src="{{ user['image'] }}" alt="" class="rounded-circle article-img">
        </div>
        <div class="col-md-2 my-auto">
            <!-- Name -->
            <p><b>{{ user['name'] }}</b></p>
        </div>
        <div class="col-md-3 my-auto">
            <!-- Email -->
            <p>{{ user['email'] }}</p>
        </div>
        <div class="col-md-5 my-auto">
            <div class="row">
                <div class="col-md-4">
                <a href="{{ url_for('admin.user_profile', uid=user['uid']) }}"><button class="btn btn-info">View Profile</button></a>

            </div>
            <div class="col-md-4">
                <a href="{{ url_for('messanger.chat', key=user['uid']  ) }}"><button class="btn btn-info">Message</button></a>
            </div>
            <div class="col-md-4">
                <button class="btn btn-danger">Delete</button>
            </div>

            </div>

        </div>

    </div>
    {% endfor %}
</div>

<script type="text/javascript" >

    $(document).ready(function()
    {
      var page = $("#home");
      $(".nav-item").removeClass("active");
      page.addClass("active")
    });

  </script>


{% endblock content %}

MyApp/templates/admin_order.html
{% extends "layout.html" %}
{% block content %}

<h1 class="mt-5 myFonts" >Orders</h1>
<hr><br>

<div class="row mt-3 h-100 justify-content-center align-items-center">

    
    <div class="col-md-3 col-sm-3 p-2 my-auto text-center border">
        <!-- name -->
        <p class="myFonts" ><b>Clint</b></p>
    </div>
    <div class="col-md-4 col-sm-4 p-2 my-auto text-center border">
        <!-- dish name -->
        <p class="myFonts" ><b>Dish</b></p>
    </div>
    <!-- <div class="col-md-2 my-auto ">
         dish icon
        <b></b>
    </div> -->
    <div class="col-md-1 col-sm-1 p-2 my-auto text-center border">
        <!-- quantity -->
        <p class="myFonts" ><b>Quantity</b></p>
    </div>
    <div class="col-md-2 col-sm-2 p-2 my-auto text-center border">
        <!-- quantity -->
        <p class="myFonts" ><b>Location</b></p>
    </div>
    
    <div class="col-md-2 col-sm-2 p-2 my-auto text-center border">
        <p class="myFonts" ><b>Action</b></p>
    </div>    

</div>

{% if objectList %}
{% for k in objectList %}

       
    <div class="row mt-3 h-100 justify-content-center align-items-center">

        <div class="col-md-1">
            <!-- image -->
            <img class="rounded-circle article-img" src="{{k['clintPhotoUri']}}" alt="image">
        </div>
        <div class="col-md-2 my-auto">
            <!-- name -->
           <a href="{{ url_for('admin.user_profile', uid=k['clintUID'] ) }}"><p>{{k['clintName']}}</p></a> 
        </div>
        <div class="col-md-2 my-auto">
            <!-- dish name -->
            <p>{{k['dishName']}}</p>
        </div>
        <div class="col-md-2 my-auto">
            <!-- dish icon -->
            <img class="rounded " src="{{ k['dishImageUri'] }}" alt="image" width="30px" height="30px">
        </div>
        <div class="col-md-1 my-auto text-center">
            <!-- quantity -->
            <p>{{k['dishQuantity']}}</p>
        </div>
        <div class="col-md-2 my-auto text-center">
            <!-- quantity -->
            <p>{{k['clintLocation']}}</p>
        </div>
        
        <div class="col-md-2 my-auto text-center">
            {% if k['accepted'] == true %}

                {% if k['completed'] %}
                    <button class="btn btn-success smgd" disabled >Completed</button>
                {% else %}
                    <button class="btn btn-success smgd" disabled >Accepted </button>
                {% endif %}
    
            {% else %}

                {% if k['cancelled'] %}
                    <button class="btn btn-danger smgd" disabled >Cancelled</button>
                {% else %}
                    <button class="btn btn-info btn-outline-info smgd" value="{{k['clintUID'] + k['orderTime']}}" > Accept  </button>
                {% endif %}
                
            {% endif %}
        </div>    
    
    </div>

{% endfor %}
{% endif %}


<script type="text/javascript">
$(document).ready(function() {

$( "button" ).click(function() {
    var data = $(this).val();
    var self = $(this);
    console.log(data)
    $.ajax({
            url: '/accept_process',
            datatype : 'application/json;charset=UTF-8',
			data: {"data": data},
			type: 'POST',
			success: function(response){
                console.log(response);
                self.removeClass("btn-info btn-outline-info").addClass("btn-success");
                self.attr('disabled' , 'disabled').text("Accepted");
			},
			error: function(error){
				console.log(error);
			}
		});
});

      var page = $("#Order");
      $(".nav-item").removeClass("active");
      page.addClass("active")

});
</script>





{% endblock %}

MyApp/templates/chat.html
{% extends "layout.html" %}

{% block content %}

<div class="container">
<h3 class=" text-center">Messaging</h3>
<div class="messaging">
      <div class="inbox_msg">
        <div class="inbox_people">
          <div class="headind_srch">
            <div class="recent_heading">
              <h4>Recent</h4>
            </div>
            <div class="srch_bar">
              <div class="stylish-input-group">
                <input type="text" class="search-bar"  placeholder="Search" >
                <span class="input-group-addon">
                <button type="button" > <i class="fa fa-search" aria-hidden="true"></i> </button>
                </span> </div>
            </div>
          </div>
          <div class="inbox_chat">

          </div>
        </div>
        <div class="mesgs">
          <div class="msg_history">

            {% for k,v in first_person_data.items() %}

            {% if v['senderId'] != "17352015" %}
            <div class="incoming_msg">
              <div class="incoming_msg_img"> <img src="{{ v['senderProfileURI'] }}" alt="sunil"> </div>
              <div class="received_msg">
                <div class="received_withd_msg">
                  <p>{{ v['msg'] }}</p>
                  <span class="time_date"> {{ v['msgTime']|time  }} </span></div>
              </div>
            </div>
            {% elif v['senderId'] == "17352015" %}
            <div class="outgoing_msg">
              <div class="sent_msg">
                <p> {{ v['msg'] }} </p>
                <span class="time_date"> {{ v['msgTime']|time  }} </span> </div>
            </div>
            {% else %}
            {% endif %}
            {% endfor %}
            
          </div>
          <div class="type_msg">
            <div class="input_msg_write">
              <input type="text" class="write_msg" placeholder="Type a message" />
              <button id="send_btn" class="msg_send_btn" type="button" value="{{senderID}}" ><i class="fa fa-paper-plane-o" aria-hidden="true"></i></button>
            </div>
          </div>
        </div>

      </div>
      
      
      <p class="text-center top_spac"> Design by <a target="_blank" href="#">Sunil Rajput</a></p>
      
    </div></div>




{% endblock %}

MyApp/templates/chat_room.html
{% extends "layout.html" %}

{% block content %}

<div class="container">
  <h3 class=" text-center">Messaging</h3>

    <div class="mesgs">
      <div class="msg_history">

        {% for key,val in data.items() %}
        
        {% if val['senderId'] != '17352015' %}
        <div class="incoming_msg">
          <div class="incoming_msg_img rounded-circle"> <img src="{{ val['senderProfileUri'] }}" alt="Profile Picture"> </div>
          <div class="received_msg">
            <div class="received_withd_msg">
              <p>{{ val['msg'] }}</p>
              <span class="time_date"> {{ val['msgTime']|time }}</span></div>
          </div>
        </div>

        {% elif val['senderId'] == '17352015' %}

        <div class="outgoing_msg">
          <div class="sent_msg">
            <p>{{ val['msg'] }}</p>
            <span class="time_date"> {{ val['msgTime']|time }}</span> </div>
        </div>
        {% else %}

        {% endif %}
        
        {% endfor %}
  
        <ul id="messages">
          <li>Shakeel</li>
        </ul>
      


      </div>
      <div class="type_msg">
        <div class="input_msg_write">
          <input type="text" class="write_msg" placeholder="Type a message" />
          <button class="msg_send_btn" type="button"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></button>
        </div>
      </div>
    </div>

</div>


{% endblock %}

MyApp/templates/foods_add.html
{% extends "layout.html" %}

{% block content %}
<div id="form-div">

    <form action="{{ url_for('foods.process_data') }}" method="POST" enctype="multipart/form-data" class="border p-3">

        <div class="form-group">
            <label for="foodName">Food Name</label>
            <input name="foodName" type="text" class="form-control" id="foodName">
        </div>
    
        <div class="form-group">
            <label for="foodPrice">Food Price</label>
            <input name="foodPrice" type="number" class="form-control" id="foodPrice">
        </div>
    
        <div class="form-group">
            <label for="foodImage"></label>
            <input name="foodImage" type="file" class="form-control-file" id="foodImage">
        </div>
    
        <div class="form-group">
            <button type="submit" class="btn btn-primary" > ADD FOODS </button>
        </div>
    
    
    </form>
    
    

</div>


<script type="text/javascript" >

    $(document).ready(function()
    {
      var page = $("#add_foods");
      $(".nav-item").removeClass("active");
      page.addClass("active")
    });

  </script>




{% endblock content %}

MyApp/templates/foods_list.html
{% extends "layout.html" %}
{% block content %}

<h1 class="mt-5 myFonts" > <b>Foods List</b> </h1>

<div class="row mt-3">

    {% for k,v in data.items() %}
    <div class="col-md-4 mt-3">
        
        <div class="card" style="width: 18rem;">
            <img class="card-img-top bg-danger" src="{{ v['foodImageUri'] }}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">{{ v['foodName'] }}</h5>
              {% if v['availability'] %}
              <button class="btn btn-success" itemName="{{ v['foodName'] }}" con="t" disabled>Available</button>
              <button class="btn btn-outline-primary"  itemName="{{ v['foodName'] }}" con="f" > Not Available</button>
              {% else %}
              <button class="btn btn-outline-success" itemName="{{ v['foodName'] }}" con="t" >Available</button>
              <button class="btn btn-primary "  itemName="{{ v['foodName'] }}" con="f" disabled > Not Available</button>
              {% endif %}
            </div>
          </div>
        
    </div>
    {% endfor %}

</div>


<script type="text/javascript">
  $(document).ready(function() {
  

  $( "button" ).click(function() {
      var self = $(this);
      var itemName = $(this).attr("itemName");
      var con = $(this).attr("con");
      var condition = false;
      if(con == "t")
      {
        condition = true;
      }
      else{
        condition = false;
      }

      $.ajax({
              url: '/foods_list/availability',
              datatype : 'application/json;charset=UTF-8',
              data: {"itemName": itemName, "condition" : condition },
              type: 'POST',
              success: function(response)
              {
                
                  var res =  JSON.parse(response);
                  var con = res['condition']
                  console.log(con)
                  if(con)
                  {
                    
                  }
                  else
                  {
                    
                  }
              },
              error: function(error)
              {
                    console.log(error);
              }
            });
  });
  
      var page = $("#foods_list");
      $(".nav-item").removeClass("active");
      page.addClass("active")


  });
  </script>
  


{% endblock %}

MyApp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V8</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="../static/images//icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../static/css/util.css">
	<link rel="stylesheet" type="text/css" href="../static/css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form method="POST" action="{{ url_for('admin.admin_login') }}" class="login100-form validate-form p-l-55 p-r-55 p-t-178">
					
					<span class="login100-form-title">
						Sign In
					</span>

					<div class="wrap-input100 validate-input m-b-16" data-validate="Please enter email">
						<input class="input100" type="text" name="email" placeholder="email">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Please enter password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
					</div>

					<div class="text-right p-t-13 p-b-23">
						
					</div>

					<div class="container-login100-form-btn">
						<button type="submit" class="login100-form-btn">
							Sign in
						</button>
					</div>

					<div class="flex-col-c p-t-170 p-b-40">
						<span class="txt1 p-b-9">
							
						</span>

						<a href="" class="txt3">
							
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	
<!--===============================================================================================-->
	<script src="../static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="../static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="../static/vendor/bootstrap/js/popper.js"></script>
	<script src="../static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="../static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="../static/vendor/daterangepicker/moment.min.js"></script>
	<script src="../static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="../static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="../static/js/main.js"></script>

</body>
</html>

MyApp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- JQuery -->
    <script
  src="https://code.jquery.com/jquery-3.5.0.js"
  integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc="
  crossorigin="anonymous"></script>
<!-- Socketio -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.8/socket.io.min.js"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font awesom -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet"/>

     <!-- Custom CSS -->
     <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}" >
     <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/chatStyle.css') }}" >
     <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/foodStyle.css') }}" >

    {% if title %}
        <title>Flask Blog - {{ title}} </title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      
      <div class="container">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark-red">
          <a class="navbar-brand input-serach" href="#">IUSM</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item " id="home" >
                <a class="nav-link" href="{{ url_for('admin.admin_main') }}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item" id="Order" >
                <a class="nav-link" href="{{ url_for('admin.admin_order') }}">Order</a>
              </li>
              <li class="nav-item" id="foods_list" >
                <a class="nav-link " href="{{ url_for('foods.foods_list') }}">Foods</a>
              </li>
              <li class="nav-item" id="add_foods" >
                <a class="nav-link " href="{{ url_for('foods.add_foods') }}">Add Foods</a>
              </li>
            </ul>
            

            <ul class="navbar-nav ml-auto">
              <li class="nav-item mr-3">
                <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2 input-serach" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0 input-serach" type="submit">Search</button>
                </form>
              </li>
              <li class="nav-item" id="logout" >
                  <a class="nav-link " href="{{ url_for('admin.logout') }}">Logout</a>
              </li>
            </ul>
            
          </div>
        </nav>

      </div>
      </header>

      <main role="main" class="container">
        
        {% block content %}
        {% endblock %}

      </main>


      



    <!-- Optional JavaScript -->
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</body>
</html>

MyApp/templates/login.html
{% extends "layout.html" %}

{% block content %}



{% endblock content %}